function h=mark_electrodes_cont(subject_name,dataroute,channel_list,channel_values)
%mark_electrodes(mapfile,locfile,channel_list)
%Mark the significant channels on a surface map(generated by freesurfer)
%Mark them with continuous color representating siginificance

% Revised from ZhengXiao's mapping_system by Chen Song, 2013-7-9

locfile=[dataroute,subject_name,'_loc.mat'];
mapfile=[dataroute,subject_name,'_surface.png'];
load(locfile);   %name 'loc' and saved in acquire_loc.m
skull=imread(mapfile);
load('label_norm.mat');    %named label_norm, a constant list
%usually locfile has the same order as 'label_norm' in sc_toolbox
skull_cover=zeros(size(skull));

signif_chan=[];
for i=1:length(channel_list);
    indx=find(strcmp(channel_list{i},label_norm));
    signif_chan=[signif_chan,indx];
end
for ii=1:length(signif_chan)
    fff=signif_chan(ii);
    skull_cover(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,1)=channel_values(ii);
    skull_cover(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,2)=0;
    skull_cover(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,3)=0;
end
skull_cover=squeeze(skull_cover(:,:,1));

h=figure;
imagesc(skull),axis equal, axis off, hold on;
h2=contour(skull_cover,'LineWidth',3);axis equal; axis off;
colormap('hot');
% saveas(h,[patientName '\\result_hand'],'jpg');