function h=mark_electrodes_mapping(subject_name,dataroute,channel_list,montage)
%mark_electrodes(subject_name,dataroute,channel_list)
%Mark the significant channels on a surface map(generated by freesurfer)

% Revised from ZhengXiao's mapping_system by Chen Song, 2013-7-9

%INPUT
%subject_name : subject's name
%dataroute : location of subject's picture, required as 'subject's name_mapping.png'
%channel_list : channels to be marked, such as 'Amp1-1'
%montage:
%1 : 64 channel, Amp1~4
%2 : 92 channel, Amp1~6

%OUTPUT
%The figure of marking electrodes on the head

%PARAMETERS
%the locfile's order should be
%"Amp1-1~16";"Amp2-1~16";..."Amp5-1~16";"Amp6-5~16"; use label_92
%Probably "Amp1-1~16" ... "Amp4-1~16";   use label_norm
%The electrode can also be less than montage's channel number.


%exp.
%dataroute='D:\mapping\ChenLonglong\';
%subjInfo.name='ChenLonglong';
%remaining_labels=[1:32,34:40,42:64];
%load('label_norm');
%channel_list=label_norm(remaining_labels);
%montage=1;
%h=mark_electrodes_mapping(subjInfo.name,dataroute,channel_list,montage)


locfile=[dataroute,subject_name,'_mapping_loc.mat'];
mapfile=[dataroute,subject_name,'_mapping.png'];
load(locfile);   %name 'loc' and saved in acquire_loc.m
skull=imread(mapfile);

switch montage
    case 1
        load('label_norm.mat');    %named label_norm, a constant list
        %usually locfile has the same order as 'label_norm' in sc_toolbox
        label_list=label_norm;
    case 2
        load('label_92.mat');  
        label_list=label_92;
    otherwise
        error('Montage not found!');
end

signif_chan=[];
for i=1:length(channel_list);
    indx=find(strcmp(channel_list{i},label_list));
    signif_chan=[signif_chan,indx];
end
for ii=1:length(signif_chan)
    fff=signif_chan(ii);
    skull(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,1)=255;
    skull(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,2)=0;
    skull(loc(fff,2)-9:loc(fff,2)+9,loc(fff,1)-9:loc(fff,1)+9,3)=0;
end
h=figure;
imagesc(skull),axis equal, axis off
% saveas(h,[patientName '\\result_hand'],'jpg');